version: '3'

services:

  payload:
    container_name: payload
    image: node:18.15.0-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongodb:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
      DB_HOST: mongodb

  mongo:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
